DEBUG 2023-11-02 15:55:10.918 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-11-02 15:55:10.918 UTC: 	 Running on: Linux lxplus762.cern.ch 3.10.0-1160.99.1.el7.x86_64 #1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-11-02 15:55:10.918 UTC: 	 Executing command: 'getoutput'
DEBUG 2023-11-02 15:55:10.919 UTC: 	 Found CRAB cache file /afs/cern.ch/user/l/lfavilla/.crab3
ERROR 2023-11-02 15:55:10.949 UTC: 	 Error: ./crab_TT_Mtt_700to1000_2018/ is not a valid CRAB project directory.
ERROR 2023-11-02 15:55:10.949 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: Error: ./crab_TT_Mtt_700to1000_2018/ is not a valid CRAB project directory.
INFO 2023-11-02 15:55:10.951 UTC: 	 Log file is /afs/cern.ch/user/l/lfavilla/CMSSW_12_6_0/src/PhysicsTools/NanoAODTools/crab/macros/crab.log
DEBUG 2023-11-02 15:58:33.870 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-11-02 15:58:33.870 UTC: 	 Running on: Linux lxplus762.cern.ch 3.10.0-1160.99.1.el7.x86_64 #1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-11-02 15:58:33.870 UTC: 	 Executing command: 'getoutput'
DEBUG 2023-11-02 15:58:33.870 UTC: 	 Found CRAB cache file /afs/cern.ch/user/l/lfavilla/.crab3
ERROR 2023-11-02 15:58:33.872 UTC: 	 Error: ../crabTT_hadr_2018/ is not a valid CRAB project directory.
ERROR 2023-11-02 15:58:33.872 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: Error: ../crabTT_hadr_2018/ is not a valid CRAB project directory.
INFO 2023-11-02 15:58:33.874 UTC: 	 Log file is /afs/cern.ch/user/l/lfavilla/CMSSW_12_6_0/src/PhysicsTools/NanoAODTools/crab/macros/crab.log
DEBUG 2023-11-02 16:02:04.944 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-11-02 16:02:04.944 UTC: 	 Running on: Linux lxplus762.cern.ch 3.10.0-1160.99.1.el7.x86_64 #1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-11-02 16:02:04.944 UTC: 	 Executing command: 'getoutput'
DEBUG 2023-11-02 16:02:04.944 UTC: 	 Found CRAB cache file /afs/cern.ch/user/l/lfavilla/.crab3
ERROR 2023-11-02 16:02:04.951 UTC: 	 Error: ../crabTT_Mtt_1000toInf_2018/ is not a valid CRAB project directory.
ERROR 2023-11-02 16:02:04.951 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: Error: ../crabTT_Mtt_1000toInf_2018/ is not a valid CRAB project directory.
INFO 2023-11-02 16:02:04.955 UTC: 	 Log file is /afs/cern.ch/user/l/lfavilla/CMSSW_12_6_0/src/PhysicsTools/NanoAODTools/crab/macros/crab.log
DEBUG 2023-11-02 16:02:26.232 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-11-02 16:02:26.232 UTC: 	 Running on: Linux lxplus762.cern.ch 3.10.0-1160.99.1.el7.x86_64 #1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-11-02 16:02:26.232 UTC: 	 Executing command: 'getoutput'
DEBUG 2023-11-02 16:02:26.232 UTC: 	 Found CRAB cache file /afs/cern.ch/user/l/lfavilla/.crab3
ERROR 2023-11-02 16:02:26.234 UTC: 	 Error: ../crabTT_Mtt_1000toInf_2018/ is not a valid CRAB project directory.
ERROR 2023-11-02 16:02:26.234 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: Error: ../crabTT_Mtt_1000toInf_2018/ is not a valid CRAB project directory.
INFO 2023-11-02 16:02:26.237 UTC: 	 Log file is /afs/cern.ch/user/l/lfavilla/CMSSW_12_6_0/src/PhysicsTools/NanoAODTools/crab/macros/crab.log
DEBUG 2023-11-07 15:33:21.529 UTC: 	 CRAB Client version: v3.231010
DEBUG 2023-11-07 15:33:21.529 UTC: 	 Running on: Linux lxplus736.cern.ch 3.10.0-1160.99.1.el7.x86_64 #1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-11-07 15:33:21.529 UTC: 	 Executing command: 'getoutput'
DEBUG 2023-11-07 15:33:21.530 UTC: 	 Found CRAB cache file /afs/cern.ch/user/l/lfavilla/.crab3
ERROR 2023-11-07 15:33:21.642 UTC: 	 Error: ./crab_TT_semilep_2018/ is not a valid CRAB project directory.
ERROR 2023-11-07 15:33:21.642 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 644, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: Error: ./crab_TT_semilep_2018/ is not a valid CRAB project directory.
INFO 2023-11-07 15:33:21.691 UTC: 	 Log file is /afs/cern.ch/user/l/lfavilla/CMSSW_12_6_0/src/PhysicsTools/NanoAODTools/crab/macros/crab.log
DEBUG 2023-11-07 15:33:41.440 UTC: 	 CRAB Client version: v3.231010
DEBUG 2023-11-07 15:33:41.440 UTC: 	 Running on: Linux lxplus736.cern.ch 3.10.0-1160.99.1.el7.x86_64 #1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-11-07 15:33:41.440 UTC: 	 Executing command: 'getoutput'
DEBUG 2023-11-07 15:33:41.440 UTC: 	 Found CRAB cache file /afs/cern.ch/user/l/lfavilla/.crab3
ERROR 2023-11-07 15:33:41.442 UTC: 	 Error: ./crab_TT_semilep_2018/ is not a valid CRAB project directory.
ERROR 2023-11-07 15:33:41.442 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 644, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: Error: ./crab_TT_semilep_2018/ is not a valid CRAB project directory.
INFO 2023-11-07 15:33:41.444 UTC: 	 Log file is /afs/cern.ch/user/l/lfavilla/CMSSW_12_6_0/src/PhysicsTools/NanoAODTools/crab/macros/crab.log
